swagger: "2.0"
info:
  version: "0.0.1"
  title: Swagger Demo
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /people/{personId}:
    # binds app logic to a route
    x-swagger-router-controller: Person
    get:
      description: Returns a single person
      # used as the method name of the controller
      operationId: getPerson
      parameters:
        - name: personId
          in: path
          description: Id of the person to return
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PersonResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  PersonResponse:
    required:
      - firstName
      - lastName
    properties:
      firstName:
        type: string
      lastName:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
